# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import pets_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='person.proto',
  package='protodeco.example',
  serialized_pb='\n\x0cperson.proto\x12\x11protodeco.example\x1a\npets.proto\"\x94\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03\x61ge\x18\x02 \x02(\x05\x12*\n\x07\x66riends\x18\x03 \x03(\x0b\x32\x19.protodeco.example.Person\x12%\n\x04pets\x18\x04 \x03(\x0b\x32\x17.protodeco.example.Pets\x12\r\n\x05words\x18\x05 \x03(\t\x12\r\n\x05value\x18\x06 \x01(\t')




_PERSON = descriptor.Descriptor(
  name='Person',
  full_name='protodeco.example.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='protodeco.example.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='age', full_name='protodeco.example.Person.age', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='friends', full_name='protodeco.example.Person.friends', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pets', full_name='protodeco.example.Person.pets', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='words', full_name='protodeco.example.Person.words', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='protodeco.example.Person.value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=196,
)

_PERSON.fields_by_name['friends'].message_type = _PERSON
_PERSON.fields_by_name['pets'].message_type = pets_pb2._PETS
DESCRIPTOR.message_types_by_name['Person'] = _PERSON

class Person(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PERSON
  
  # @@protoc_insertion_point(class_scope:protodeco.example.Person)

# @@protoc_insertion_point(module_scope)
