# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='pets.proto',
  package='protodeco.example',
  serialized_pb='\n\npets.proto\x12\x11protodeco.example\"\x8a\x01\n\x04Pets\x12*\n\x04kind\x18\x01 \x02(\x0e\x32\x1c.protodeco.example.Pets.Kind\x12\x0c\n\x04name\x18\x02 \x01(\t\x12.\n\rfavorite_food\x18\x03 \x03(\x0b\x32\x17.protodeco.example.Food\"\x18\n\x04Kind\x12\x07\n\x03\x44OG\x10\x01\x12\x07\n\x03\x43\x41T\x10\x02\"#\n\x04\x46ood\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05price\x18\x02 \x01(\x05')



_PETS_KIND = descriptor.EnumDescriptor(
  name='Kind',
  full_name='protodeco.example.Pets.Kind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='DOG', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CAT', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=148,
  serialized_end=172,
)


_PETS = descriptor.Descriptor(
  name='Pets',
  full_name='protodeco.example.Pets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='kind', full_name='protodeco.example.Pets.kind', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='protodeco.example.Pets.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='favorite_food', full_name='protodeco.example.Pets.favorite_food', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PETS_KIND,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=172,
)


_FOOD = descriptor.Descriptor(
  name='Food',
  full_name='protodeco.example.Food',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='protodeco.example.Food.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price', full_name='protodeco.example.Food.price', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=174,
  serialized_end=209,
)

_PETS.fields_by_name['kind'].enum_type = _PETS_KIND
_PETS.fields_by_name['favorite_food'].message_type = _FOOD
_PETS_KIND.containing_type = _PETS;
DESCRIPTOR.message_types_by_name['Pets'] = _PETS
DESCRIPTOR.message_types_by_name['Food'] = _FOOD

class Pets(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PETS
  
  # @@protoc_insertion_point(class_scope:protodeco.example.Pets)

class Food(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FOOD
  
  # @@protoc_insertion_point(class_scope:protodeco.example.Food)

# @@protoc_insertion_point(module_scope)
